### ISSUE TITLE
todo für rev branch

### ISSUE THREAD

**Issue by cfbolz** [talpa-io/otic#2]
für @AKJ7, hier die Verbesserungen an den Tests und dem Code, die ich vorschlagen würde:

verbesserungen an den tests/der infrastruktur:

- [ ]  build commands in die .kick.yml (@dermatthes hat ein Workflow aufgesetzt, dass nach jeden commit einen Build anstößt)
- [ ] Ein Build Target, dass die test coverage des C-Codes nach dem Ausführen der Tests anzeigt
- [ ] unit tests für alle features
- [ ] tests für PHP extension

Bonus-Aufgaben wären:
- [ ] generative Tests
- [ ] fuzzing mit afl

Auf der Coding-Seite gibt es ein paar Aufräumarbeiten zu erledigen, zb gibt es einige unbenutzte `otic_type_e` Elemente, etwa `OTIC_TYPE_MIN3_FLOAT`. Außerdem sollten die Header noch in interne (wo die ganzen struct-Definitionen sichtbar sind) und externe, für die User der Bibliothek aufgespalten werden.
